use anyhow::{Context, Result, bail};
use clap::{Parser, Subcommand};
use colored::Colorize;
use indexmap::IndexSet;
use leo_bindings_core::{ResolvedUnit, ResolvedWorkspace, cross_crate_imports, resolve_workspace};
use leo_package::Location;
use leo_span::create_session_if_not_set_then;
use regex::Regex;
use std::fmt::Write;
use std::path::{Path, PathBuf};
use std::{fs, io};

const BINDINGS_GIT: &str = "https://github.com/henrikkv/leo-bindings";

#[derive(Parser)]
#[command(name = "leo-bindings")]
struct Cli {
    #[command(subcommand)]
    command: Commands,
}

#[derive(Subcommand)]
enum Commands {
    Update {
        #[arg(default_value = ".")]
        path: PathBuf,

        #[arg(short, long)]
        yes: bool,

        /// Import leo-bindings from workspace instead of github
        #[arg(long)]
        workspace: bool,
    },
}

fn main() -> Result<()> {
    leo_bindings::utils::init_simple_logger();

    let cli = Cli::parse();
    create_session_if_not_set_then(|_| match cli.command {
        Commands::Update {
            path,
            yes,
            workspace,
        } => update_bindings(&path, yes, workspace),
    })
}

fn update_bindings(project_path: &Path, auto_yes: bool, cargo_workspace: bool) -> Result<()> {
    let project_path = project_path
        .canonicalize()
        .context("Failed to resolve project path")?;

    let workspace = resolve_workspace(&project_path)?;
    let root_unit = root_program_unit(&workspace, &project_path)?;
    if !root_unit.kind().is_program() {
        bail!(
            "`{}` is a Leo library (has `src/lib.leo`, no `src/main.leo`/`src/main.aleo`).\n\
             leo-bindings update only scaffolds the project root when it is a deployable program \
             (library-root bindings are not supported yet).",
            project_path.display()
        );
    }
    let crate_name = format!("{}_bindings", root_unit.name());

    let scaffold_dir = workspace
        .workspace_root()
        .map(Path::to_path_buf)
        .unwrap_or_else(|| project_path.clone());
    let programs = workspace.programs();

    println!("{} Found {} programs", "✓".green(), programs.len());

    let file_paths = [
        scaffold_dir.join("Cargo.toml"),
        scaffold_dir.join("lib.rs"),
        scaffold_dir.join("build.rs"),
        scaffold_dir.join(".gitignore"),
    ];

    println!("\n{}", "Files to replace:".yellow().bold());
    for path in &file_paths {
        let relative_path = path.strip_prefix(&scaffold_dir).unwrap_or(path);
        println!("  {} {}", "✓".green(), relative_path.display());
    }

    if !auto_yes {
        print!("\n{} ", "Replace? [y/N]".yellow().bold());
        std::io::Write::flush(&mut io::stdout())?;
        let mut response = String::new();
        io::stdin().read_line(&mut response)?;
        if !matches!(response.trim().to_lowercase().as_str(), "y" | "yes") {
            println!("{} Cancelled.", "✗".red());
            return Ok(());
        }
    }

    println!();

    let cargo_toml_path = scaffold_dir.join("Cargo.toml");
    let preserved_imports = if cargo_toml_path.exists() {
        let existing_content = fs::read_to_string(&cargo_toml_path)?;
        let re = Regex::new(r"(?s)# BEGIN IMPORTS\n(.*?)# END IMPORTS").unwrap();
        re.captures(&existing_content)
            .and_then(|caps| caps.get(1))
            .map(|m| m.as_str().trim().to_string())
    } else {
        None
    };

    let imports_block = match preserved_imports {
        Some(preserved) if !preserved.is_empty() => {
            format!("\n# BEGIN IMPORTS\n{preserved}\n# END IMPORTS\n")
        }
        _ => default_imports_block().to_string(),
    };

    if !scaffold_dir.exists() {
        fs::create_dir_all(&scaffold_dir)?;
    }

    let cargo_toml =
        generate_cargo_toml(&crate_name, &programs, cargo_workspace, Some(imports_block));
    fs::write(&cargo_toml_path, cargo_toml).context("Failed to write Cargo.toml")?;
    fs::write(scaffold_dir.join("lib.rs"), generate_lib_rs())?;
    fs::write(scaffold_dir.join(".gitignore"), generate_gitignore())?;
    fs::write(scaffold_dir.join("build.rs"), generate_build_rs())?;

    println!("\n{} Cargo setup done!", "✓".green().bold());

    Ok(())
}

fn generate_gitignore() -> &'static str {
    r"# This file is automatically @generated by leo-bindings.
# It is not intended for manual editing.

target/
registry/
Cargo.lock

build/*
!build/*/
build/imports/*
!build/imports/*.abi.json

outputs/
"
}

fn generate_lib_rs() -> &'static str {
    r#"// This file is automatically @generated by leo-bindings.
// It is not intended for manual editing.

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
"#
}

fn generate_cargo_toml(
    crate_name: &str,
    programs: &[&leo_bindings_core::ResolvedUnit],
    workspace: bool,
    imports_block: Option<String>,
) -> String {
    let pkg_meta = if workspace {
        "version.workspace = true\nedition.workspace = true\n".to_string()
    } else {
        "version = \"0.1.0\"\nedition = \"2024\"\n".to_string()
    };

    let mut cargo_toml = format!(
        r#"# This file is automatically @generated by leo-bindings.
# It is not intended for manual editing.

[package]
name = "{crate_name}"
{pkg_meta}[lib]
name = "{crate_name}"
path = "lib.rs"

[dependencies]
"#
    );

    if workspace {
        cargo_toml.push_str("leo-bindings-sdk.workspace = true\n");
    } else {
        cargo_toml.push_str(&format!(
            "leo-bindings-sdk = {{ git = \"{BINDINGS_GIT}\" }}\n"
        ));
    }

    for dep_name in cross_crate_imports(programs) {
        if workspace {
            let _ = writeln!(cargo_toml, "{dep_name}_bindings.workspace = true");
        } else {
            let _ = writeln!(
                cargo_toml,
                "{dep_name}_bindings = {{ git = \"{BINDINGS_GIT}\" }}"
            );
        }
    }

    if let Some(block) = imports_block {
        cargo_toml.push_str(&block);
    }

    cargo_toml.push_str("\n[build-dependencies]\n");
    if workspace {
        cargo_toml.push_str("leo-bindings-core.workspace = true\n");
    } else {
        cargo_toml.push_str(&format!(
            "leo-bindings-core = {{ git = \"{BINDINGS_GIT}\" }}\n"
        ));
    }

    cargo_toml
}

fn generate_build_rs() -> &'static str {
    r#"// This file is automatically @generated by leo-bindings.
// It is not intended for manual editing.

fn main() {
    leo_bindings_core::run_bindings_build().expect("bindings build failed");
}
"#
}

fn default_imports_block() -> &'static str {
    r#"
# BEGIN IMPORTS
# END IMPORTS
"#
}

fn root_program_unit<'a>(
    workspace: &'a ResolvedWorkspace,
    project_path: &Path,
) -> Result<&'a ResolvedUnit> {
    let at_workspace_root = workspace
        .workspace_root()
        .is_some_and(|root| root == project_path);
    match workspace.units().get(project_path) {
        Some(unit) => Ok(unit),
        None if at_workspace_root => top_program_unit(workspace),
        None => bail!(
            "`{}` was not found in the resolved package set (is it a workspace member?)",
            project_path.display()
        ),
    }
}

fn top_program_unit(workspace: &ResolvedWorkspace) -> Result<&ResolvedUnit> {
    let depended_on: IndexSet<&Path> = workspace
        .units()
        .values()
        .flat_map(|unit| unit.dependencies())
        .filter(|dep| dep.location == Location::Local)
        .filter_map(|dep| dep.path.as_deref())
        .collect();

    let candidates: Vec<&ResolvedUnit> = workspace
        .programs()
        .into_iter()
        .filter(|unit| !depended_on.contains(unit.dir()))
        .collect();

    match candidates.as_slice() {
        [unit] => Ok(unit),
        [] => bail!(
            "No workspace member is a standalone program (every program is a local dependency \
             of another). Point leo-bindings at a specific member directory instead."
        ),
        _ => bail!(
            "This workspace has multiple independent programs ({}). Point leo-bindings at a \
             specific member directory to pick which one names the generated crate.",
            candidates
                .iter()
                .map(|u| u.name())
                .collect::<Vec<_>>()
                .join(", ")
        ),
    }
}
