use leo_abi_types::Program;
use leo_bindings_core::generator::{ImportRef, generate_program_module};
use proc_macro2::Span;
use std::path::PathBuf;
use syn::parse::{Parse, ParseStream};
use syn::punctuated::Punctuated;
use syn::{Error, Ident, Path, Token};

/// Generates Rust bindings for a Leo program.
#[proc_macro]
pub fn generate_bindings(input: proc_macro::TokenStream) -> proc_macro::TokenStream {
    match generate_bindings_inner(input) {
        Ok(ts) => ts,
        Err(e) => e.to_compile_error().into(),
    }
}

struct ImportArg {
    name: Ident,
    same_crate: bool,
}

struct GenerateBindingsInput {
    name: Ident,
    imports: Vec<ImportArg>,
}

impl Parse for GenerateBindingsInput {
    fn parse(input: ParseStream) -> syn::Result<Self> {
        let items: Punctuated<Path, Token![,]> = Punctuated::parse_terminated(input)?;
        let mut iter = items.into_iter();

        let name_path = iter.next().ok_or_else(|| {
            Error::new(
                Span::call_site(),
                "generate_bindings!() requires a name, e.g. generate_bindings!(my_program)",
            )
        })?;
        let name = name_path.get_ident().cloned().ok_or_else(|| {
            Error::new_spanned(
                &name_path,
                "expected a plain identifier for the program/library name",
            )
        })?;

        let imports = iter
            .map(|path| {
                let same_crate = path.segments.first().is_some_and(|s| s.ident == "crate");
                let last = path.segments.last().ok_or_else(|| {
                    Error::new_spanned(&path, "expected an identifier or `crate::name`")
                })?;
                Ok(ImportArg {
                    name: last.ident.clone(),
                    same_crate,
                })
            })
            .collect::<syn::Result<Vec<_>>>()?;

        Ok(GenerateBindingsInput { name, imports })
    }
}

fn generate_bindings_inner(input: proc_macro::TokenStream) -> syn::Result<proc_macro::TokenStream> {
    let parsed: GenerateBindingsInput = syn::parse(input)?;
    let program_name = parsed.name.to_string();

    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").map_err(|e| {
        Error::new(
            Span::call_site(),
            format!("CARGO_MANIFEST_DIR is not set: {e}"),
        )
    })?;

    let abi_path = PathBuf::from(&manifest_dir)
        .join("build")
        .join(&program_name)
        .join("abi.json");
    let json = std::fs::read_to_string(&abi_path).map_err(|e| {
        Error::new(
            parsed.name.span(),
            format!("failed to read ABI at {}: {e}", abi_path.display()),
        )
    })?;
    let abi: Program = serde_json::from_str(&json).map_err(|e| Error::new(Span::call_site(), e))?;

    let program_id = abi.program.trim_end_matches(".aleo");
    if program_id != program_name {
        return Err(Error::new(
            parsed.name.span(),
            format!(
                "generate_bindings!({program_name}, ...) does not match program '{}' read from {}",
                abi.program,
                abi_path.display()
            ),
        ));
    }

    let imports: Vec<ImportRef> = parsed
        .imports
        .iter()
        .map(|import| ImportRef {
            name: import.name.to_string(),
            same_crate: import.same_crate,
        })
        .collect();

    let import_streams: Vec<proc_macro2::TokenStream> = imports
        .iter()
        .filter(|import| !import.same_crate)
        .map(|import| {
            let import_crate =
                proc_macro2::Ident::new(&format!("{}_bindings", import.name), Span::call_site());
            let import_module = proc_macro2::Ident::new(&import.name, Span::call_site());
            quote::quote! {
                pub use ::#import_crate::#import_module;
            }
        })
        .collect();

    let program_module = generate_program_module(&abi, &imports);

    Ok(quote::quote! {
        // This file is automatically @generated by leo-bindings.
        // It is not intended for manual editing.

        #(#import_streams)*

        #program_module
    }
    .into())
}
