[package]
name = "token"
version.workspace = true
edition.workspace = true

[lib]
name = "token_bindings"
path = "lib.rs"

[dependencies]
leo-bindings.workspace = true
credits_bindings.workspace = true

[dev-dependencies]
snarkvm = { workspace = true }
rand = { workspace = true }
