[package]
name = "token"
version = "0.1.0"
edition = "2021"

[lib]
name = "tokenexample"
path = "lib.rs"

[dependencies]
leo-bindings = { path = "../../" }
leo-bindings-credits = { path = "../../leo-bindings-credits/" }
snarkvm = "4.1.0"
anyhow = "1.0"
leo-span = "3.1.0"
leo-package = "3.1.0"
leo-ast = "3.1.0"
ureq = { version = "2.6", features = ["json"] }
serde_json = "1.0"
indexmap = "2.0"
aleo-std = { version = "1.0.1", features = ["storage"] }
rand = "0.8"
