[package]
name = "token"
version.workspace = true
edition.workspace = true

[lib]
name = "tokenexample"
path = "lib.rs"

[dependencies]
leo-bindings = { path = "../../" }
leo-bindings-credits = { path = "../../leo-bindings-credits/" }
snarkvm = { workspace = true }
anyhow = { workspace = true }
leo-span = { workspace = true }
leo-package = { workspace = true }
leo-ast = { workspace = true }
ureq = { workspace = true }
serde_json = { workspace = true }
indexmap = { workspace = true }
aleo-std = { workspace = true }
rand = { workspace = true }
http = { workspace = true }
