use std::fmt::Write;
use std::path::{Path, PathBuf};
use std::process::Command;

use anyhow::{Context, Result, bail};

use crate::discover::{
    ResolvedWorkspace, cross_crate_imports, program_imports, register_rerun_if_changed,
    resolve_workspace,
};
use crate::generator::generate_program_module;

pub fn run_bindings_build() -> Result<()> {
    let manifest_path = PathBuf::from(
        std::env::var("CARGO_MANIFEST_DIR").context("CARGO_MANIFEST_DIR is not set")?,
    );
    let workspace = resolve_workspace(&manifest_path)?;
    if workspace.programs().is_empty() {
        bail!("no Leo programs found under {}", manifest_path.display());
    }

    register_rerun_if_changed(&workspace);
    ensure_leo_outputs(&manifest_path, &workspace)?;
    write_bindings(&workspace)
}

fn ensure_leo_outputs(manifest_path: &Path, workspace: &ResolvedWorkspace) -> Result<()> {
    let leo_root = workspace.leo_root(manifest_path);
    let programs = workspace.programs();

    if programs.iter().any(|unit| !unit.is_bytecode_only()) {
        println!("cargo:warning=Running leo build");
        run_leo_command(&leo_root, "build", &[])?;
    }
    for unit in programs.iter().filter(|unit| unit.is_bytecode_only()) {
        let source = unit
            .rebuild_source()
            .context("bytecode-only program has no source")?;
        let abi_path = unit.build_abi();
        let build_dir = abi_path
            .parent()
            .context("unit ABI path has no parent directory")?;
        std::fs::create_dir_all(build_dir)?;
        println!("cargo:warning=Running leo abi for '{}'", unit.name());
        run_leo_command(
            &leo_root,
            "abi",
            &[path_str(&source)?, "--output", path_str(build_dir)?],
        )?;
    }
    Ok(())
}

fn path_str(path: &Path) -> Result<&str> {
    path.to_str().context("non-UTF-8 path")
}

fn run_leo_command(cwd: &Path, subcommand: &str, args: &[&str]) -> Result<()> {
    let status = Command::new("leo")
        .arg(subcommand)
        .args(args)
        .current_dir(cwd)
        .status()
        .with_context(|| format!("failed to run `leo {subcommand}`"))?;
    if !status.success() {
        bail!("`leo {subcommand}` failed");
    }
    Ok(())
}

fn write_bindings(workspace: &ResolvedWorkspace) -> Result<()> {
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").context("OUT_DIR is not set")?);
    let bindings_dir = out_dir.join("bindings");
    std::fs::create_dir_all(&bindings_dir)?;

    let units = workspace.units();
    let programs = workspace.programs();
    for unit in &programs {
        let imports = program_imports(unit, units);
        let tokens = generate_program_module(&unit.load_abi()?, &imports);
        let file = syn::parse2(tokens).context("failed to parse generated bindings")?;
        write_if_changed(
            &bindings_dir.join(format!("{}.rs", unit.name())),
            prettyplease::unparse(&file),
        )?;
    }

    let mut root = String::from(
        "// This file is automatically @generated by leo-bindings.\n\
         // It is not intended for manual editing.\n\n",
    );
    for unit in &programs {
        writeln!(
            root,
            "include!(concat!(env!(\"OUT_DIR\"), \"/bindings/{}.rs\"));",
            unit.name()
        )?;
    }
    for name in cross_crate_imports(&programs) {
        writeln!(root, "pub use ::{name}_bindings::{name};")?;
    }
    write_if_changed(&out_dir.join("bindings.rs"), root)
}

fn write_if_changed(path: &Path, contents: impl AsRef<[u8]>) -> Result<()> {
    let contents = contents.as_ref();
    if std::fs::read(path).is_ok_and(|existing| existing == contents) {
        return Ok(());
    }
    std::fs::write(path, contents)
        .with_context(|| format!("failed to write {}", path.display()))?;
    Ok(())
}
