[workspace]

[package]
name = "token-example"
version = "0.1.0"
edition = "2024"

[dependencies]
token_bindings = { path = "../leo" }
credits_bindings = { path = "../../../leo-bindings-credits" }
leo-bindings = { path = "../../.." }

[dev-dependencies]
snarkvm = "4.2.0"
rand = "0.8"
