[package]
name = "dev"
version.workspace = true
edition.workspace = true

[lib]
name = "devtest"
path = "lib.rs"

[dependencies]
leo-bindings = { path = "../../" }

[dev-dependencies]
snarkvm = { workspace = true }
