[package]
name = "dev"
version.workspace = true
edition.workspace = true

[lib]
name = "dev_bindings"
path = "lib.rs"

[dependencies]
leo-bindings.workspace = true

[dev-dependencies]
snarkvm.workspace = true
