[package]
name = "leo-bindings-credits"
version.workspace = true
edition.workspace = true

[lib]
name = "leo_bindings_credits"
path = "lib.rs"

[features]
default = ["testnet"]
mainnet = []
testnet = []
canary = []
interpreter = []

[dependencies]
leo-bindings = { path = "../" }
