[workspace]

[package]
name = "dev-example"
version = "0.1.0"
edition = "2024"

[dependencies]
dev_bindings = { path = "../leo" }
leo-bindings = { path = "../../.." }

[dev-dependencies]
snarkvm = "4.2.0"

