[package]
name = "external"
version = "0.1.0"
edition = "2021"

[lib]
name = "external"
path = "lib.rs"

[dependencies]
leo-bindings = { git = "https://github.com/henrikkv/leo-bindings" }

[dev-dependencies]
war = { git = "https://github.com/henrikkv/berlin" }
