[package]
name = "external"
version.workspace = true
edition.workspace = true

[dependencies]
leo-bindings.workspace = true

[dev-dependencies]
war = { git = "https://github.com/henrikkv/berlin" }
snarkvm = { version = "4.2.0" }
