[package]
name = "external"
version.workspace = true
edition.workspace = true

[lib]
name = "external"
path = "lib.rs"

[features]
default = ["testnet"]
mainnet = []
testnet = []
canary = []
interpreter = []

[dependencies]
leo-bindings = { git = "https://github.com/henrikkv/leo-bindings" }

[dev-dependencies]
war = { git = "https://github.com/henrikkv/berlin" }
snarkvm = { version = "4.2.0" }
